##### Big-O Complexity 

<img src= "https://miro.medium.com/max/828/1*yekzNjsqZzGCET2KotEROQ.png">

In [ ]:
A = [-2, -4, 3, -1, 5, 6, -7, -2, 4, -3, 2]

In [ ]:
# Tutorial 1 Q5

A = [-1, 4, -5, 0]

def min_max(A):
    # Base case
    if len(A) == 1:
        return A[0], A[0]
    else:
        curr_min, curr_max = min_max(A[1:])
        return min(A[0], curr_min), max(A[0], curr_max)

min_max(A)

(-5, 4)

##### Flowchart for Q5

<img src= "https://www.dropbox.com/s/wtwok7v0hvvu4i7/mh1403_tut1_q5.png?dl=1">

In [ ]:
# Tutorial 1 Q7
# First calculate the sum of the integers from i = 1 to i = n-1. Then, calculate the sum of all values in the array A. 
# The missing element is the difference between these two numbers.

In [ ]:
# Tutorial 1 Q8
# An O(n) algorithm for finding row with most '1' in array of 1 and 0,
# assuming '1' comes before '0'. This method uses a pointer (p) to store
# row number with most '1'. When column index j has a 0 entry, row index i
# is incremented to check if there is another '1' at the [i+1][j] entry
# The process terminates once index i or j reaches the row/column number

import numpy as np

# Test array (4x4)
A = np.array([[1,1,0,0],[1,0,0,0],[0,0,0,0],[1,0,0,0]])
print(A)
print(A.shape)

def find_row(A):
    i = 0
    j = 0
    p = 0
    while j < A.shape[1]:
        if A[i][j] == 1:
            p = i
            j += 1
            continue
        elif i == A.shape[0] - 1:
            return p
        else:
            i += 1
    return i

find_row(A)

[[1 1 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
(4, 4)


0

In [ ]:
# Tutorial 1 Q9
# Recursive algorithm to compute product of 2 positive integers
# Observe the following recurrence relation, m*n = m + (n-1)*m

def multiply(m, n):
    # Base case
    if n == 1:
        return m
    else:
        product = m + multiply(m, n-1)
    return product

multiply(6,5)

30

In [ ]:
# Tutorial 1 Q10
# A simple first solution to reverse a list
# Note that this solution takes 0(n) additional space since we are creating a new list!

s = [3,4,1,5]

def reverser(s):
    n = len(s)
    new_s = []
    for i in range(n-1,-1,-1):
        new_s.append(s[i])
    return new_s

reverser(s)

# This solution utilizes pointers at start (p1) and end (p2) of list
# and swops the value of the list at each index (position of pointer)
# Then we increment p1 and decrement p2 until p1 >= p2
# This is an in-place reversal so it does not take any additional space unlike the slicing [::-1] method

def reverser_2(s):
    p1 = 0
    p2 = len(s) - 1
    while p1 < p2:
        temp = s[p1]
        s[p1] = s[p2]
        s[p2] = temp
        p1 += 1
        p2 -= 1
    return s

reverser_2(s)

[5, 1, 4, 3]

In [ ]:
# Tutorial 1 Q11
# An O(n) algorithm for finding the longest subarray of an n element array
# such that the elements of the subarray are in sorted order. This method uses
# two pointers (subarr_start, subarr_end) to store index of longest sorted subarray.
# Then we compute the difference between the two indexes. The result is stored in a
# tuple with the corresponding indexes. Then we iterate over the tuples to find the
# largest difference, which will then give us the indexes of the subarray.

A = [4, 9, 5, 7, 3, 4, 5, 3, 9, 1, 1]


def find_subarr_sorted(A):
    n = len(A)
    subarr_start = 0
    subarr_end = 0
    pdiff = []
    for i in range(n-1):
        if A[i+1] > A[i]:
            subarr_end += 1
            continue
        else:
            p = subarr_end - subarr_start
            pdiff.append((p, subarr_start, subarr_end))
            subarr_start = i+1
            subarr_end = i+1

    #print(pdiff)
    largest = 0
    maxindex = 0
    for j in range(len(pdiff)):
        if pdiff[j][0] > largest:
            largest = pdiff[j][0]
            maxindex = j
        else:
            continue
    start = pdiff[maxindex][1]
    end = pdiff[maxindex][2]
    return A[start:end+1]

find_subarr_sorted(A)

[(1, 0, 1), (1, 2, 3), (2, 4, 6), (1, 7, 8), (0, 9, 9)]


[3, 4, 5]

In [ ]:
# Tutorial 1 Q12
# A simple first solution to find unique element of a list that runs in O(n^2) time

A = [1,1,2,4,2,5,4]

def find_unique(A):
    copy = []
    for element in A:
        if element not in copy:
            copy.append(element)
            A.remove(element)     # Runs in O(n) time!
    for element in copy:
        if element not in A:
            unique = element
            break
    return unique

find_unique(A)

5

Bit Manipulation and XOR function
--


#### About the algorithm


<img src= "https://codepumpkin.com/wp-content/uploads/2017/07/XOR-uniqueElementFromArray.jpg" width="640" height="480">  

- Recall the binary representation of integers in decimal  

- The `XOR(^)` of a number **> 0** with itself is 0, i.e. `n ^ n = 0`, e.g:  

  <img src= "https://codepumpkin.com/wp-content/uploads/2017/07/5XOR5.jpg">  
  
- XOR is commutative, i.e. `x ^ y = y ^ x`, so the XOR of all the elements in our array is: <img src= "https://codepumpkin.com/wp-content/uploads/2017/07/XORExplanation.jpg">  

- Even number of `XOR` of a number produces 0, `n ^ n = 0`

- Odd number of `XOR` of a number produces the number itself, `n ^ n ^ n = (n ^ n) ^ n = 0 ^ n = n`


In [ ]:
# Q12 Solution that runs in O(n) time using XOR operator
# Solution only works if A is an array of positive (> 0) integers

A = [1,1,2,4,2,5,4]

def find_unique_2(A):
    n = len(A)
    result = A[0]
    for i in range(n-1):
        result = A[i+1] ^ result
    return result

find_unique_2(A)

5